### PR TITLE
Making sure python3 is executed and not 2

### PR DESCRIPTION
**Pull request by truhlikfredy**
On systems with python2 and python3 this will make sure the 3 is executed every time

### CODE REVIEW

**Comment by ebrian** [comment]
Looks good to me. GitDummy works with both but this will also pick up the case when it's being executed without prepending "python" to the beginning of the command.

**Comment by truhlikfredy** [comment]
When I used 2.7.9 python it tried to get access to mouse cursor. This problem got away when python3 was used.

**Comment by ebrian** [comment]
Odd. No need for control of the mouse cursor in this program. Just for my own curiosity, what leads you to believe it tried to get access to your mouse cursor?

**Comment by truhlikfredy** [comment]
./gitdummy.py
    import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9199.
    import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9199.
    import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9199.
    ./gitdummy.py: line 9: syntax error near unexpected token `('
    ./gitdummy.py: line 9: `if not os.path.isfile('repos.json'):'

Probably I have something mis-configured on my side which makes the **os** import misbehave, but with **env** people can still force it to run with python 2 if they want. And this way you don't need to execute it with python as first.

**Comment by ebrian** [comment]
Yeah, that seems odd. I'm satisfied with the change though. Python 3 works for me. We'll always try to maintain compatibility with both since Python 2 is still very widely used.

**Pull request merged**
